# Configuration for Kodiak's auto-merge tool
# see full options: https://kodiakhq.com/docs/config-reference

version = 1 # this is required but 1 is currently the only option

[update]
always = true # default: false
require_automerge_label = false # default: true
automerge_label = "automerge" # default: automerge
# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
ignored_usernames = ["dependabot"]

[merge]
# if a PR is ready, merge it, don't place it in the merge queue.
prioritize_ready_to_merge = true # default: false
# will not do anything if a matching label is applied
blocking_labels = ["DO NOT MERGE"]
method = "squash"

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
#versions = ["minor", "patch"]
#usernames = ["dependabot"]

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".

# auto_approve_usernames = ["dependabot"]
auto_approve_usernames = ["RBusarow"]

[merge.message]
# use title of PR for merge commit.
title = "pull_request_title" # default: "github_default"

# use body of PR for merge commit.
body = "pull_request_body" # default: "github_default"

# add the PR number to the merge commit title, like GitHub.
include_pr_number = true # default: true

# use the default markdown content of the PR for the merge commit.
body_type = "markdown" # default: "markdown"

# remove html comments to auto remove PR templates.
strip_html_comments = true # default: false

include_pull_request_url = true # default: false
