site_name: 'Dispatch'
site_description: 'Quality of life coroutine utilities.'
site_author: '2020 Rick Busarow'
site_url: 'https://rbusarow.github.io/Dispatch/'
remote_branch: gh-pages
docs_dir: '../docs'

# Repository
repo_name: 'Dispatch'
repo_url: 'https://github.com/rbusarow/dispatch'

# Copyright
copyright: 'Copyright &copy; 2020 Rick Busarow'

# Customization
extra:
  social:
    - type: github
      link: https://github.com/rbusarow/dispatch
    - type: twitter
      link: https://twitter.com/rbusarow
    - type: linkedin
      link: https://linkedin.com/in/rick-busarow

nav:
  - 'Intro': index.md
  #  - 'Getting Started': getting-started.md
  - 'Modules':
      - 'Core': modules/dispatch-core.md
      - 'Detekt': modules/dispatch-detekt.md
      - 'Test':
          - 'Test-Core': modules/dispatch-test.md
          - 'Test-JUnit4': modules/dispatch-test-junit4.md
          - 'Test-JUnit5': modules/dispatch-test-junit5.md
      - 'Android':
          - 'Android-Espresso': modules/dispatch-android-espresso.md
          - 'Android-Lifecycle': modules/dispatch-android-lifecycle.md
          - 'Android-Lifecycle-Extensions': modules/dispatch-android-lifecycle-extensions.md
          - 'Android-Viewmodel': modules/dispatch-android-viewmodel.md
  #  - 'Change Log':
  - 'Change Log': CHANGELOG.md
  - 'KDoc':
      - 'core': kdoc/dispatch-core/index.md
      - 'detekt': kdoc/dispatch-detekt/index.md
      - 'test-core': kdoc/dispatch-test/index.md
      - 'test-junit4': kdoc/dispatch-test-junit4/index.md
      - 'test-junit5': kdoc/dispatch-test-junit5/index.md
      - 'android-espresso': kdoc/dispatch-android-espresso/index.md
      - 'android-lifecycle': kdoc/dispatch-android-lifecycle/index.md
      - 'android-lifecycle-extensions': kdoc/dispatch-android-lifecycle-extensions/index.md
      - 'android-viewmodel': kdoc/dispatch-android-viewmodel/index.md

theme:
  name: 'material'

  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: True
      use_pygments: True
      noclasses: True
  #      pygments_style: monokai
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
