site_name: 'Dispatch'
site_description: 'Quality of life coroutine utilities.'
site_author: '2020 Rick Busarow'
site_url: 'https://rbusarow.github.io/Dispatch/'
remote_branch: gh-pages
docs_dir: '../docs'

# Repository
repo_name: 'Dispatch'
repo_url: 'https://github.com/rbusarow/dispatch'

# Copyright
copyright: 'Copyright &copy; 2020 Rick Busarow'

# Customization
extra:
  social:
    - type: github
      link: https://github.com/rbusarow/dispatch
    - type: twitter
      link: https://twitter.com/rbusarow
    - type: linkedin
      link: https://linkedin.com/in/rick-busarow

nav:
  - 'Intro': index.md
  #  - 'Getting Started': getting-started.md
  - 'Modules':
      - 'Core': modules/core.md
      - 'Extensions': modules/extensions.md
      - 'Test-Core': modules/core-test.md
      - 'Test-JUnit4': modules/core-test-junit4.md
      - 'Test-JUnit5': modules/core-test-junit5.md
      - 'Android-Espresso': modules/android-espresso.md
      - 'android-lifecycle': modules/android-lifecycle.md
      - 'Android-viewmodel': modules/android-viewmodel.md
  #  - 'Change Log':
  - 'Change Log': CHANGELOG.md
  - 'KDoc':
      - 'core': kdoc/core/index.md
      - 'extensions': kdoc/extensions/index.md
      - 'test-core': kdoc/core-test/index.md
      - 'test-junit4': kdoc/core-test-junit4/index.md
      - 'test-junit5': kdoc/core-test-junit5/index.md
      - 'android-espresso': kdoc/android-espresso/index.md
      - 'android-lifecycle': kdoc/android-lifecycle/index.md
      - 'android-viewmodel': kdoc/android-viewmodel/index.md

theme:
  name: 'material'

  language: en
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: True
      use_pygments: True
      noclasses: True
  #      pygments_style: monokai
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
