[versions]
androidTools = "4.2.0"
androidxTest = "1.3.0"
androidxTestEspresso = "3.3.0"
anvil = "2.2.1"
benManes = "0.36.0"
changeTracker = "0.7.3"
compileSdk = "30"
coroutines = "1.4.3"
dependencyAnalysis = "0.63.0"
dispatch = "1.0.0-beta09"
detekt =  "1.16.0"
dokka = "1.4.10"
gradleDoctor = "0.7.0"
groovy = "3.0.8"
hermit = "0.9.3"
jUnit = "5.7.1"
knit = "0.2.3"
kotest = "4.5.0"
kotlin = "1.5.0"
kotlinter = "3.4.0"
mavenPublish = "0.13.0"
minSdk = "23"
sonarPlugin = "2.6.1"
spoon = "1.5.0"
spotless = "5.10.1"
targetSdk = "30"
taskTree = "1.5"
versionName = "0.10.0"

[libraries]

androidx-activity = "androidx.activity:activity-ktx:1.2.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.2.0"
androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-coreKtx = "androidx.core:core-ktx:1.3.2"

androidx-fragment-core = "androidx.fragment:fragment:1.3.3"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.3.3"
androidx-fragment-testing = "androidx.fragment:fragment-testing:1.3.3"

androidx-lifecycle-common = "androidx.lifecycle:lifecycle-common:2.3.1"
androidx-lifecycle-extensions = "androidx.lifecycle:lifecycle-extensions:2.3.1"
androidx-lifecycle-liveData = "androidx.lifecycle:lifecycle-livedata-core:2.3.1"
androidx-lifecycle-liveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime:2.3.1"
androidx-lifecycle-runtimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
androidx-lifecycle-viewModel = "androidx.lifecycle:lifecycle-viewmodel:2.3.1"
androidx-lifecycle-viewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"

androidx-test-jUnit = "androidx.test.ext:junit:1.1.2"

androidx-arch-test-core = "androidx.arch.core:core-testing:2.1.0"

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidxTest" }

androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidxTestEspresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-espresso-idlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidxTestEspresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidxTestEspresso" }
androidx-test-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "androidxTestEspresso" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidTools" }
anvil = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
javaParser = "com.github.javaparser:javaparser-symbol-solver-core:3.20.2"
javax-inject = "javax.inject:javax.inject:1"

detekt-api ={ module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-cli = { module ="io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-formatting ={ module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-test ={ module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

dispatch-core = { module = "com.rickbusarow.dispatch:dispatch-core", version.ref = "dispatch" }
dispatch-detekt = { module = "com.rickbusarow.dispatch:dispatch-detekt", version.ref = "dispatch" }
dispatch-espresso = { module = "com.rickbusarow.dispatch:dispatch-android-espresso", version.ref = "dispatch" }
dispatch-lifecycle = { module = "com.rickbusarow.dispatch:dispatch-android-lifecycle", version.ref = "dispatch" }
dispatch-lifecycleExtensions = { module = "com.rickbusarow.dispatch:dispatch-android-lifecycle-extensions", version.ref = "dispatch" }
dispatch-viewModel = { module = "com.rickbusarow.dispatch:dispatch-android-viewmodel", version.ref = "dispatch" }
dispatch-test-core = { module = "com.rickbusarow.dispatch:dispatch-test", version.ref = "dispatch" }
dispatch-test-jUnit4 = { module = "com.rickbusarow.dispatch:dispatch-test-junit4", version.ref = "dispatch" }
dispatch-test-jUnit5 = { module = "com.rickbusarow.dispatch:dispatch-test-junit5", version.ref = "dispatch" }

kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testCommon = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }

kotlinPoet = "com.squareup:kotlinpoet:1.8.0"

kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }

kotlinx-atomicfu = "org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.16.1"

kotlinx-coroutines-common = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-common", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

kotlinx-knit-test = "org.jetbrains.kotlinx:kotlinx-knit-test:0.2.3"

semVer = "net.swiftzer.semver:semver:1.1.1"

groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovyXml = { module = "org.codehaus.groovy:groovy-xml", version.ref = "groovy" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jUnit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jUnit" }
junit-junit4 = "junit:junit:4.13.2"

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-assertionsShared = { module = "io.kotest:kotest-assertions-shared-jvm", version.ref = "kotest" }
kotest-common-jvm = { module = "io.kotest:kotest-common-jvm", version.ref = "kotest" }
kotest-properties = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }

hermit-core = { module = "com.rickbusarow.hermit:hermit-core", version.ref = "hermit" }
hermit-jUnit4 = { module = "com.rickbusarow.hermit:hermit-junit4", version.ref = "hermit" }
hermit-jUnit5 = { module = "com.rickbusarow.hermit:hermit-junit5", version.ref = "hermit" }
hermit-mockk = { module = "com.rickbusarow.hermit:hermit-mockk", version.ref = "hermit" }
hermit-coroutines = { module = "com.rickbusarow.hermit:hermit-coroutines", version.ref = "hermit" }

mockk = "io.mockk:mockk:1.11.0"

robolectric = "org.robolectric:robolectric:4.5.1"

timber = "com.jakewharton.timber:timber:4.7.1"

[bundles]
jUnit = ["junit-api", "junit-params", "junit-engine"]
kotest = ["kotest-assertions", "kotest-properties", "kotest-runner"]
hermit = ["hermit-core", "hermit-jUnit5"]
