/*
 * Copyright (C) 2021 Rick Busarow
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports = {
//  mySidebar: [
//    {
//      type: 'autogenerated',
//      dirName: '.', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
//    },
//  ],
  Docs: [
    "intro",
    "quickstart",
    "modules/dispatch-core",
    "modules/dispatch-detekt",
    {
      type: "category",
      label: "Android",
      collapsed: false,
      items: [
        "modules/dispatch-android-espresso",
        "modules/dispatch-android-lifecycle",
        "modules/dispatch-android-lifecycle-extensions",
        "modules/dispatch-android-viewmodel",
      ],
    },
    {
      type: "category",
      label: "Testing",
      collapsed: false,
      items: [
        "modules/dispatch-test",
        "modules/dispatch-test-junit4",
        "modules/dispatch-test-junit5",
      ],
    },
  ]
}
;
