name: CI

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every day at 10pm CST (4 UTC)
    - cron: '0 4 * * *'

jobs:

  cancel-other-jobs:

    runs-on: ubuntu-latest

    steps:
      # cancel previous jobs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        env:
          access_token: '${{ github.token }}'

  detekt:

    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          cache: 'gradle'

      - uses: burrunan/gradle-cache-action@v1
        name: detekt
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            detekt --no-daemon
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false

  ktlint:

    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          cache: 'gradle'

      # formats all src files
      - uses: burrunan/gradle-cache-action@v1
        name: KtLint format
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            ktlintFormat
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false

      # If KtLint generated changes, commit and push those changes.
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply KtLint format
          commit_options: '--no-verify --signoff'

#  versioning:
#
#    runs-on: ubuntu-latest
#    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: ${{ github.event.pull_request.head.ref }}
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          fetch-depth: 0
#
#      - name: Set up JDK
#        uses : actions/setup-java@v2
#        with :
#          distribution : 'adopt'
#          java-version : '14'
#          cache: 'gradle'
#
#      - uses: burrunan/gradle-cache-action@v1
#        name: Sync versions in website docs
#        with:
#          gradle-dependencies-cache-key: |
#            gradle/libs.versions.toml
#          arguments: |
#            updateWebsiteNextDocsVersionRefs
#          concurrent: true
#          gradle-build-scan-report: false
#          gradle-distribution-sha-256-sum-warning: false
#
#      - name: commit changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: update docs versions
#          commit_options: '--no-verify --signoff'
#
#      - uses: burrunan/gradle-cache-action@v1
#        name: Update version in website package.json
#        with:
#          gradle-dependencies-cache-key: |
#            gradle/libs.versions.toml
#          arguments: |
#            updateWebsitePackageJsonVersion
#          concurrent: true
#          gradle-build-scan-report: false
#          gradle-distribution-sha-256-sum-warning: false
#
#      - name: commit changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: update website versions
#          commit_options: '--no-verify --signoff'

  api-check:

    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          cache: 'gradle'

      - uses: burrunan/gradle-cache-action@v1
        name: api check
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            apicheck
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          cache: 'gradle'

      - uses: burrunan/gradle-cache-action@v1
        name: all tests
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            testJvm
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false
