name: DependencySync

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  cancel-other-jobs:

    runs-on: ubuntu-latest

    steps:
      # cancel previous jobs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        env:
          access_token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

      - name: Set up JDK
        uses: actions/setup-java@v1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          java-version: 14

      - name: Copy Dependabot dependencies to toml
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        run: ./gradlew dependencySync

      # If the copy generated changes, commit and push those changes.
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          commit_message: Update dependencies from dependabot
          commit_options: '--no-verify --signoff'
