name: deploy-website

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v1

      # Install and build Docusaurus website
      - name: Install yarn dependencies
        run: |
          cd website
          yarn install

      - uses: burrunan/gradle-cache-action@v1
        name: Build Docusaurus website
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            buildSite
          concurrent: true
          gradle-build-scan-report: false

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
